name: mcbike
description: A web shop for motocross equipment built with Flutter.
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: "3.1.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  carousel_slider: ^4.2.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^4.1.3
  #integration_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/landing_image.png
    - assets/motocb1.avif
    - assets/motocb4.jpg
    #   - assets/images/   # Uncomment if directory of images

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  web: true
